[template]
src = "sshd_config.tmpl"
dest = "/etc/ssh/sshd_config"
keys = [
    "/sshd/port",
    "/sshd/addressfamily",
    "/sshd/listenaddress/*",
    "/sshd/hostkey",
    "/sshd/rekeylimit",
    "/sshd/syslogfacility",
    "/sshd/loglevel",
    "/sshd/logingracetime",
    "/sshd/permitrootlogin",
    "/sshd/strictmodes",
    "/sshd/maxauthtries",
    "/sshd/maxsessions",
    "/sshd/pubkeyauthentication",
    "/sshd/authorizedkeysfile",
    "/sshd/authorizedprincipalsfile",
    "/sshd/authorizedkeyscommand",
    "/sshd/authorizedkeyscommanduser",
    "/sshd/hostbasedauthentication",
    "/sshd/ignoreuserknownhosts",
    "/sshd/ignorerhosts",
    "/sshd/passwordauthentication",
    "/sshd/permitemptypasswords",
    "/sshd/challengeresponseauthentication",
    "/sshd/kerberosauthentication",
    "/sshd/kerberosorlocalpasswd",
    "/sshd/kerberosticketcleanup",
    "/sshd/kerberosgetafstoken",
    "/sshd/gssapiauthentication",
    "/sshd/gssapicleanupcredentials",
    "/sshd/usepam",
    "/sshd/allowagentforwarding",
    "/sshd/allowtcpforwarding",
    "/sshd/gatewayports",
    "/sshd/x11forwarding",
    "/sshd/x11displayoffset",
    "/sshd/x11uselocalhost",
    "/sshd/permittty",
    "/sshd/printmotd",
    "/sshd/printlastlog",
    "/sshd/tcpkeepalive",
    "/sshd/uselogin",
    "/sshd/permituserenvironment",
    "/sshd/compression",
    "/sshd/clientaliveinterval",
    "/sshd/clientalivecountmax",
    "/sshd/usedns",
    "/sshd/pidfile",
    "/sshd/maxstartups",
    "/sshd/permittunnel",
    "/sshd/chrootdirectory",
    "/sshd/versionaddendum",
    "/sshd/banner",
    "/sshd/subsystem",
    "/sshd/tcprcvbufpoll",
    "/sshd/hpndisabled",
    "/sshd/hpnbuffersize",
    "/sshd/match",
    "/sshd/x11forwarding",
    "/sshd/allowtcpforwarding",
    "/sshd/permittty",
    "/sshd/forcecommand"
]